// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One provider's auth/liveness state — the wire shape of
 * [`crate::auth::ProviderAuth`] for `GET /api/doctor`.
 */
export type AuthState = "ready" | "needs_login" | "cli_missing" | "down";
