// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/config` — a read-only summary of the council the server runs
 * with. Roles are `provider/model` strings for display, not for editing.
 */
export type ConfigSummary = { conductor: string, workers: Array<string>, reviewer: string, chairman: string, supervisor: string, cross_family_review: boolean, budget_secs: number | null, 
/**
 * Where the config was loaded from (`null` = built-in defaults).
 */
config_path: string | null, };
