// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderStatus } from "./ProviderStatus";

/**
 * `GET /api/doctor` — live auth/liveness report for every provider.
 */
export type DoctorReport = { providers: Array<ProviderStatus>, };
