// Barrel for the WebSocket + REST protocol. The sibling modules are generated by
// ts-rs (see README.md); this file is the only hand-written one.
export type { Provider } from './Provider'
export type { AgentEvent } from './AgentEvent'
export type { ServerFrame } from './ServerFrame'
export type { SessionRequest } from './SessionRequest'
export type { ProviderUsage } from './ProviderUsage'
export type { QuotaSnapshot } from './QuotaSnapshot'
export type { AuthState } from './AuthState'
export type { ProviderStatus } from './ProviderStatus'
export type { DoctorReport } from './DoctorReport'
export type { ConfigSummary } from './ConfigSummary'
export type { VersionInfo } from './VersionInfo'
export type { CommandSource } from './CommandSource'
export type { ExecutionMode } from './ExecutionMode'
export type { ProviderReadiness } from './ProviderReadiness'
export type { ReadinessState } from './ReadinessState'
export type { RepositoryKind } from './RepositoryKind'
export type { RepositoryState } from './RepositoryState'
export type { RoleAssignment } from './RoleAssignment'
export type { SafetyPreflightReport } from './SafetyPreflightReport'
export type { VerificationCommand } from './VerificationCommand'

import type { AgentEvent } from './AgentEvent'
import type { ServerFrame } from './ServerFrame'

/**
 * Every frame the server can push on a `/ws/session` socket. Live engine events
 * (`AgentEvent`) and server lifecycle frames (`ServerFrame`) share the on-wire
 * `type` discriminant namespace, so a client switches over the single `type`.
 */
export type InboundFrame = AgentEvent | ServerFrame

/** The accepted terminal frame, narrowed from `ServerFrame`. */
export type RunComplete = Extract<ServerFrame, { type: 'run_complete' }>
