// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-provider token usage over the reporting window.
 */
export type ProviderUsage = { input_tokens: number, output_tokens: number, };
