// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-provider token usage over the reporting window.
 */
export type ProviderUsage = { input_tokens: number, output_tokens: number, 
/**
 * True when these tokens are heuristic estimates (the provider's CLI reports
 * no usage, e.g. Gemini via the Antigravity `agy` CLI) rather than measured.
 */
estimated: boolean, };
