// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthState } from "./AuthState";
import type { Provider } from "./Provider";

/**
 * One provider row in the doctor report.
 */
export type ProviderStatus = { provider: Provider, state: AuthState, 
/**
 * Probe failure detail (empty when ready).
 */
detail: string, 
/**
 * One-line actionable next step (e.g. the exact login command).
 */
hint: string, };
