// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadinessState } from "./ReadinessState";

export type ProviderReadiness = { provider: string, state: ReadinessState, detail: string, hint: string, probed: boolean, };
