// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderUsage } from "./ProviderUsage";

/**
 * A snapshot of quota usage per provider over the rolling window — served at
 * `GET /api/quota` for the dashboard.
 */
export type QuotaSnapshot = { 
/**
 * The window length the totals cover, in seconds.
 */
window_secs: number, claude: ProviderUsage, codex: ProviderUsage, gemini: ProviderUsage, };
