// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadinessState = "unknown_not_probed" | "ready" | "needs_login" | "cli_missing" | "down";
