// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryKind } from "./RepositoryKind";

export type RepositoryState = { canonical_path: string, git_root: string | null, kind: RepositoryKind, head: string | null, clean: boolean, tracked_dirty: Array<string>, untracked: Array<string>, branch: string | null, };
