// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionMode } from "./ExecutionMode";
import type { ProviderReadiness } from "./ProviderReadiness";
import type { RepositoryState } from "./RepositoryState";
import type { RoleAssignment } from "./RoleAssignment";
import type { VerificationCommand } from "./VerificationCommand";

export type SafetyPreflightReport = { repository: RepositoryState, default_mode: ExecutionMode, available_modes: Array<ExecutionMode>, commands: Array<VerificationCommand>, command_digest: string, roles: Array<RoleAssignment>, provider_readiness: Array<ProviderReadiness>, timeout_secs: number, budget_secs: number | null, provider_probe_performed: boolean, warnings: Array<string>, };
