// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server→client run-lifecycle frames. The tags are disjoint from every
 * [`AgentEvent`](crate::event::AgentEvent) tag, so a client can discriminate
 * the whole inbound stream on the single `type` field.
 */
export type ServerFrame = { "type": "run_complete", 
/**
 * Accepted subtask ids, in order.
 */
completed: Array<number>, 
/**
 * Set if the supervisor halted the run.
 */
halted: string | null, 
/**
 * Set if the conductor failed the run or rework was exhausted.
 */
failed: string | null, } | { "type": "run_error", error: string, } | { "type": "error", error: string, };
