// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client→server request: the first frame on a `/ws/session` socket.
 */
export type SessionRequest = { "kind": "conduct", task: string, context: string, 
/**
 * Working directory the run edits; defaults to the server's cwd.
 */
cwd: string | null, };
