// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client→server frames on a `/ws/session` socket: the first frame describes
 * the run; `{"kind":"cancel"}` at any later point aborts it.
 */
export type SessionRequest = { "kind": "conduct", task: string, context: string, 
/**
 * Working directory the run edits; defaults to the server's cwd.
 */
cwd: string | null, } | { "kind": "cancel" } | { "kind": "pause" } | { "kind": "resume" } | { "kind": "interject", text: string, };
