// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandSource } from "./CommandSource";

export type VerificationCommand = { label: string, command: string, source: CommandSource, timeout_secs: number, };
