// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/version` — the server's crate version.
 */
export type VersionInfo = { version: string, };
